.travis.yml, README.md, examples/server.js, lib/node-minify.js, package.json, test/node-minify.js
=> Add sync option

Readme.md
=> Update Readme with links to install Java

examples/public/css/sample3.css, test/node-minify.js
=> Add more tests for css

lib/setup.js
=> Fix public folder with wildcards on Windows

Readme.md
=> Update Readme for Babili

examples/server.js
=> Update server.js examples

.travis.yml, appveyor.yml
=> Use NPM v4 when node 7

lib/compressors/babili.js
=> Require babel preset babili

.codeclimate.yml, .eslintrc, .travis.yml, LICENSE, Readme.md, circle.yml, index.js, lib/compress.js, lib/compressors/babili.js, lib/compressors/clean-css.js, lib/compressors/csso.js, lib/compressors/gcc-java.js, lib/compressors/gcc.js, lib/compressors/no-compress.js, lib/compressors/sqwish.js, lib/compressors/uglifyjs.js, lib/compressors/yui.js, lib/deprecated.js, lib/node-minify.js, lib/runner.js, lib/setup.js, lib/utils.js, package.json, test/node-minify.spec.js, yarn.lock
Preparing merge of 2.1.0
- Use Jest #132 (980c5287f8486f5b499153fe8fb23ccbe6f8171b)
- Remove Bluebird in favor of native promises (2c2ddcf466bc4e672670e92ca2197322bfc7b542)
- Bump UglifyJS to 3.0.0 (c2d43e3d33a416dea196b79d7da3cec386fd9af9)
- Use Code Climate #146 (a473da750ad9aff973a045109cb47341d4127f2c 5be096461d40fd112910093d91d1e0f2dcf2dc69 0115c5328df4dc8f01eb7fbdfb3336a6cf580b1d)
- Add Butternut #149 (b07ff47c77dd6fbb6082b9585d2531f46a818c18 845c75d029993b2a70a19aedea31662f375d4d4e)
=> Merge Develop to Master: 2.1.0

lib/compressors/gcc.js
Hi,
I've created a small change to allow GCC options to be passed.
=> GCC Options

__tests__/node-minify-test.js, examples/server.js, lib/compress.js, lib/compressors/babili.js, lib/compressors/butternut.js, lib/compressors/clean-css.js, lib/compressors/csso.js, lib/compressors/gcc-java.js, lib/compressors/gcc.js, lib/compressors/no-compress.js, lib/compressors/sqwish.js, lib/compressors/uglifyjs.js, lib/compressors/yui.js, lib/node-minify.js, lib/runner.js
sync option was breaked because of promises, reverting to callback
=> fix(sync): fixing sync option #65

lib/compressors/gcc.js
When createSourceMap option is passed write the contents of contentMinified.sourceMap
=> Write sourceMap file for GCC

Readme.md, __tests__/node-minify-test.js, lib/compressors/gcc.js
* prettier GCC
* update Readme.md with new option createSourceMap
* update test for new option createSourceMap
=> feat(gcc): finalize PR #228

package-lock.json, package.json, yarn.lock
=> fix(package): update node-version to version 1.1.3

lib/compressors/uglifyjs.js, package-lock.json, package.json, yarn.lock
uglify-js don't compress es2015+ javascript
=> fix(uglifyjs): use uglify-es instead of uglify-js

__tests__/node-minify-test.js, lib/compress.js, lib/compressors/uglify-es.js, package-lock.json, package.json, yarn.lock
=> feat(compressor): add uglify-es

lib/compressors/gcc-java.js, lib/compressors/gcc.js, package-lock.json, package.json, yarn.lock
Switch to google-closure-compiler, fix #361
=> feat(gcc): update GCC

bin/cli.js, lib/cli/index.js
=> feat(cli): add silence option

__tests__/node-minify-test.js, docs/options.md, examples/server.js, lib/compress.js, lib/compressors/babel-minify.js, lib/compressors/butternut.js, lib/compressors/clean-css.js, lib/compressors/crass.js, lib/compressors/csso.js, lib/compressors/gcc-java.js, lib/compressors/gcc.js, lib/compressors/html-minifier.js, lib/compressors/no-compress.js, lib/compressors/sqwish.js, lib/compressors/uglify-es.js, lib/compressors/uglifyjs.js, lib/compressors/yui.js, lib/setup.js, lib/utils.js
* add the ability to use the replacement $1
* $1 will be replaced by the file name from input file
Related to #417
=> feat(output): allow the variable $1

lib/compressors/html-minifier.js, lib/setup.js, package-lock.json, package.json, yarn.lock
=> feat(package): remove xtend

Readme.md, __tests__/node-minify-test.js, bin/cli.js, docs/.vuepress/config.js, docs/README.md, docs/compressors/terser.md, examples/server.js, lib/compress.js, lib/compressors/terser.js, package-lock.json, package.json, yarn.lock
=> feat(compressor): add Terser

Readme.md, packages/babel-minify/README.md, packages/clean-css/README.md, packages/cli/README.md, packages/core/README.md, packages/crass/README.md, packages/csso/README.md, packages/google-closure-compiler/README.md, packages/html-minifier/README.md, packages/no-compress/README.md, packages/run/README.md, packages/sqwish/README.md, packages/terser/README.md, packages/uglify-es/README.md, packages/uglify-js/README.md, packages/utils/README.md, packages/yui/README.md
=> docs(lerna): add documentation

Migrate.md
=> docs(migrate): update Migrate.md

docs/README.md, docs/cli.md, docs/compressors/babel-minify.md, docs/compressors/clean-css.md, docs/compressors/crass.md, docs/compressors/csso.md, docs/compressors/gcc.md, docs/compressors/html-minifier.md, docs/compressors/sqwish.md, docs/compressors/terser.md, docs/compressors/uglify-es.md, docs/compressors/uglify-js.md, docs/compressors/yui.md, docs/getting-started.md, docs/options.md
=> docs(vuepress): update docs for 4.0.0

package.json, packages/babel-minify/package.json, packages/clean-css/package.json, packages/cli/bin/cli.js, packages/cli/package.json, packages/core/package.json, packages/crass/package.json, packages/csso/package.json, packages/google-closure-compiler/package.json, packages/html-minifier/package.json, packages/no-compress/package.json, packages/sqwish/package.json, packages/terser/package.json, packages/uglify-es/package.json, packages/uglify-js/package.json, packages/yui/package.json
=> fix(deps): fix missing deps

package.json, packages/babel-minify/package.json, packages/clean-css/package.json, packages/cli/bin/cli.js, packages/cli/package.json, packages/core/package.json, packages/crass/package.json, packages/csso/package.json, packages/google-closure-compiler/package.json, packages/html-minifier/package.json, packages/no-compress/package.json, packages/sqwish/package.json, packages/terser/package.json, packages/uglify-es/package.json, packages/uglify-js/package.json, packages/yui/package.json
- fix missing deps (#488) (790c095e983f4b0ba1191db9684940620c7340df)
=> Merge Develop to Master: 4.0.0

lerna.json, packages/babel-minify/package.json, packages/clean-css/package.json, packages/cli/package.json, packages/core/package.json, packages/crass/package.json, packages/csso/package.json, packages/google-closure-compiler/package.json, packages/html-minifier/package.json, packages/no-compress/package.json, packages/run/package.json, packages/sqwish/package.json, packages/terser/package.json, packages/uglify-es/package.json, packages/uglify-js/package.json, packages/utils/package.json, packages/yui/package.json
=> Merge Develop to Master: 4.0.2

.eslintrc, Readme.md, docs/.vuepress/config.js, docs/README.md, docs/compressors/cssnano.md, examples/server.js, packages/cssnano/README.md, packages/cssnano/__tests__/cssnano.test.js, packages/cssnano/package.json, packages/cssnano/src/cssnano.js, packages/sqwish/__tests__/sqwish.test.js, tests/files-path.js, tests/fixtures/css-errors/fixture-1-error.css, yarn.lock
=> feat(packages): add cssnano

packages/uglify-es/src/uglify-es.js
=> fix issue #685

packages/utils/src/utils.js
=> Make the $1 work for non .js files

examples/server.js, packages/babel-minify/src/babel-minify.js, packages/clean-css/__tests__/clean-css.test.js, packages/clean-css/src/clean-css.js, packages/core/__tests__/core.test.js, packages/core/src/compress.js, packages/core/src/compressInMemory.js, packages/core/src/core.js, packages/core/src/setup.js, packages/crass/src/crass.js, packages/cssnano/src/cssnano.js, packages/csso/src/csso.js, packages/google-closure-compiler/src/google-closure-compiler.js, packages/html-minifier/src/html-minifier.js, packages/no-compress/src/no-compress.js, packages/sqwish/src/sqwish.js, packages/terser/src/terser.js, packages/uglify-es/src/uglify-es.js, packages/uglify-js/src/uglify-js.js, packages/utils/src/utils.js, packages/yui/src/yui.js, tests/files-path.js, tests/fixtures.js
No more input or output
closes #659
=> feat(in-memory): add the ability to use memory

Readme.md, docs/getting-started.md
=> docs(in-memory): add documentation

docs/options.md, examples/public/html/1/html1.html, examples/public/html/2/html2.html, examples/public/html/3/html3.html, examples/public/html/html-root.html, examples/public/html/html1.html, examples/public/html/html2.html, examples/public/html/html3.html, examples/server.js, packages/core/src/setup.js, packages/utils/src/utils.js, tests/fixtures.js
add 'replaceInPlace' option
it allow saving files in same folder than source file
close #734
=> feat(replace-in-place): save in source folder

packages/cli/bin/cli.js
=> fix(cli): exit process when successful

examples/server.js, examples/server.mjs, packages/core/package.json, packages/core/src/setup.ts, pnpm-lock.yaml, renovate.json
* error when importing with commonjs
=> fix(core): rollback globby to v11

package.json, packages/babel-minify/src/index.ts, packages/clean-css/src/index.ts, packages/cli/src/compress.ts, packages/cli/src/spinner.ts, packages/core/src/compress.ts, packages/core/src/index.ts, packages/core/src/setup.ts, packages/csso/src/index.ts, packages/google-closure-compiler/src/index.ts, packages/html-minifier/src/index.ts, packages/jsonminify/src/index.ts, packages/run/src/index.ts, packages/sqwish/src/index.ts, packages/terser/src/index.ts, packages/types/src/types.ts, packages/uglify-es/src/index.ts, packages/uglify-js/src/index.ts, packages/utils/src/index.ts, packages/yui/src/index.ts, tests/fixtures.ts, tests/types.ts
refactor(packages): better typing
=> refactor(packages): better typing
